import type { MetadataRoute } from "next";

/**
 * Web App Manifest — the installable cookbook.
 *
 * Next.js App Router serves the output at /manifest.webmanifest and
 * automatically emits the <link rel="manifest"> tag in every page.
 *
 * The app identity is the COOKBOOK: start_url opens /cookbook (the
 * app-shell recipe index) rather than the long marketing one-pager, so
 * the icon on a phone behaves like a recipe book, not a brochure. Scope
 * stays "/" so recipe pages and the rest of the site open in-app when
 * navigated to. The ?source=pwa marker splits app sessions out in GA.
 *
 * Icons: launchers crop maskable icons to a circle/squircle, so the
 * maskable set keeps the skull inside the safe zone on a cream plate
 * (generated by scripts/build-pwa-icons.py). Cream background + theme
 * keep the splash screen on brand: paper, not a black rectangle.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "TOORN at table · Cookbook",
    short_name: "TOORN",
    description:
      "The cookbook of a Michelin-trained private chef on the Costa del Sol. Real recipes, by hand, in your pocket. Works offline.",
    id: "/cookbook",
    start_url: "/cookbook?source=pwa",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#F4EDE0",
    theme_color: "#F4EDE0",
    lang: "en",
    categories: ["food", "lifestyle"],
    icons: [
      {
        src: "/icons/any-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/any-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    shortcuts: [
      {
        name: "Cookbook",
        url: "/cookbook?source=pwa-shortcut",
        icons: [{ src: "/icons/any-192.png", sizes: "192x192" }],
      },
      {
        name: "This week to your door",
        url: "/the-table?source=pwa-shortcut",
      },
      {
        name: "Book a night",
        url: "/?source=pwa-shortcut#contact",
      },
    ],
  };
}
