import type { Recipe } from "@/lib/types";

/**
 * Concept recipes — written in Nick's voice as placeholders until the real
 * cookbook copy lands. The Supabase backend, when wired up, will replace
 * this array. Keep the same shape (`Recipe[]`) if you edit anything here.
 */
export const recipes: Recipe[] = [
  {
    slug: "gazpacho-andaluz",
    title: "Gazpacho andaluz",
    intro:
      "De koudste, helderste tomatensoep van de zomer — Andalusië in een glas. Lekker met een scheutje sherry erbij.",
    category: "voor",
    seasons: ["zomer"],
    difficulty: 1,
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 4,
    pairing: "Manzanilla in mooie hoge glazen.",
    body: "Maak hem 's ochtends. Niet later. Geef de smaken de hele dag om in te trekken en serveer 'm net niet ijskoud — dan voel je de tomaat het beste.",
    ingredients: [
      { quantity: "1 kg", ingredient: "rijpe vleestomaten, in grove stukken" },
      { quantity: "1", ingredient: "kleine komkommer, geschild, in stukken" },
      { quantity: "1", ingredient: "rode paprika, in stukken" },
      { quantity: "1 teen", ingredient: "knoflook" },
      { quantity: "1 sneetje", ingredient: "oudbakken witbrood" },
      { quantity: "3 el", ingredient: "Spaanse olijfolie extra vergine" },
      { quantity: "2 el", ingredient: "sherryazijn" },
      { quantity: "snufje", ingredient: "fijn zeezout" },
      { group: "Garnituur", quantity: "1 hand", ingredient: "geroosterde croutons" },
      { group: "Garnituur", quantity: "1 el", ingredient: "fijngesneden bieslook of basilicum" },
      { group: "Garnituur", quantity: "scheutje", ingredient: "extra olijfolie om af te maken" },
    ],
    steps: [
      { position: 1, body: "Doe tomaten, komkommer, paprika, knoflook en het brood in een blender. Pureer fijn tot een dikke soep." },
      { position: 2, body: "Giet er, terwijl de blender draait, de olijfolie in een dunne straal bij. Zo emulgeert de soep en wordt 'ie zijdezacht." },
      { position: 3, body: "Breng op smaak met sherryazijn en zout. Proef. Zout-zuur balans moet op het scherpst van de snede staan." },
      { position: 4, body: "Zet minimaal 3 uur in de koelkast, liefst een hele dag. De smaken trekken samen, de kleur wordt dieper rood." },
      { position: 5, body: "Schenk in koud-geslagen glazen. Top met croutons, kruiden en een laatste druppel olie. Serveer ongeveer 8°C — niet kouder, anders verlies je smaak." },
    ],
  },
  {
    slug: "carrillera-iberica",
    title: "Carrillera ibérica met sherry",
    intro:
      "Iberico-wangetjes die langzaam gaar trekken in oloroso sherry tot de vork erin verdwijnt. Comfort food met een Andalusisch accent.",
    category: "hoofd",
    seasons: ["herfst", "winter"],
    difficulty: 3,
    prepMinutes: 20,
    cookMinutes: 180,
    servings: 4,
    pairing: "Een glas van dezelfde oloroso. Of een zware Garnacha.",
    body: "Drie uur stoofwerk waar je nauwelijks naar om hoeft te kijken. Begin om twee uur, eet om zes. Schepje aardappelpuree erbij en je bent klaar.",
    ingredients: [
      { quantity: "8 stuks", ingredient: "iberico-wangetjes (ca. 1,2 kg)" },
      { quantity: "2 el", ingredient: "bloem voor het bestuiven" },
      { quantity: "3 el", ingredient: "olijfolie" },
      { quantity: "2", ingredient: "uien, fijngesneden" },
      { quantity: "3 teentjes", ingredient: "knoflook, geplet" },
      { quantity: "2", ingredient: "wortels, in dobbelstenen" },
      { quantity: "1 tak", ingredient: "rozemarijn" },
      { quantity: "2 blaadjes", ingredient: "laurier" },
      { quantity: "300 ml", ingredient: "oloroso sherry" },
      { quantity: "400 ml", ingredient: "runderbouillon" },
      { quantity: "1 el", ingredient: "geconcentreerde tomatenpuree" },
      { quantity: "naar smaak", ingredient: "zout en zwarte peper" },
    ],
    steps: [
      { position: 1, body: "Dep de wangetjes droog, bestrooi royaal met zout en peper, bestuif licht met bloem." },
      { position: 2, body: "Verhit olijfolie in een gietijzeren pan. Schroei de wangetjes rondom dichtbruin — twee minuten per kant, niet stapelen. Haal uit de pan." },
      { position: 3, body: "Bak ui, wortel en knoflook in dezelfde pan tot zacht en goudbruin, zo'n 10 minuten. Roer tomatenpuree erdoor en bak nog een minuut mee." },
      { position: 4, body: "Blus af met de oloroso. Laat reduceren met de helft, zodat het scherpe alcoholtje verdwijnt. Doe de wangetjes terug, voeg de bouillon, rozemarijn en laurier toe." },
      { position: 5, body: "Breng tegen de kook aan, dek af, schuif in een oven van 140°C. Stoof minimaal 2,5 uur — vork moet er moeiteloos in glijden." },
      { position: 6, body: "Haal de wangetjes uit de saus, zet kort apart. Reduceer de saus op een hoog vuur tot 'ie als stroop aan de lepel hangt. Proef op zout." },
      { position: 7, body: "Leg de wangetjes terug in de saus, draai 'm rustig door elkaar zodat alles glanst. Direct serveren met aardappelpuree of een sneetje geroosterd brood." },
    ],
  },
  {
    slug: "tarta-de-santiago",
    title: "Tarta de Santiago",
    intro:
      "De Galicische amandeltaart. Eén ingrediënt boven alles: een goede amandel. Geen meel, geen poespas — alleen amandelmeel, ei, suiker, citroen.",
    category: "dessert",
    seasons: ["altijd"],
    difficulty: 2,
    prepMinutes: 15,
    cookMinutes: 35,
    servings: 8,
    pairing: "Een glaasje pedro ximénez of een sterke koffie.",
    body: "Glutenvrij voordat dat een ding werd. Werkt nog beter een dag na het bakken — geef hem 'm de tijd om vochtig te worden.",
    ingredients: [
      { quantity: "250 g", ingredient: "amandelmeel (fijn gemalen, niet ontvet)" },
      { quantity: "200 g", ingredient: "fijne kristalsuiker" },
      { quantity: "4", ingredient: "eieren, op kamertemperatuur" },
      { quantity: "1", ingredient: "citroen, geraspte schil" },
      { quantity: "snufje", ingredient: "kaneel" },
      { quantity: "klontje", ingredient: "boter voor de bakvorm" },
      { group: "Afwerking", quantity: "naar smaak", ingredient: "poedersuiker om te bestuiven" },
      { group: "Afwerking", quantity: "1", ingredient: "papieren Santiago-kruis-stencil (optioneel)" },
    ],
    steps: [
      { position: 1, body: "Verwarm de oven voor op 175°C. Beboter een ronde springvorm van 24 cm of bekleed 'm met bakpapier." },
      { position: 2, body: "Klop eieren met suiker met een handmixer minstens 5 minuten — het moet bleek en luchtig zijn." },
      { position: 3, body: "Roer citroenrasp en kaneel erdoor. Spatel daarna in twee delen het amandelmeel erdoor. Niet te lang doorroeren, je wil de lucht bewaren." },
      { position: 4, body: "Schenk in de vorm, strijk glad. Bak 30-35 minuten — bovenkant goudbruin, prikker komt droog uit het midden." },
      { position: 5, body: "Laat helemaal afkoelen. Leg dan het kruis-stencil op de taart en bestuif royaal met poedersuiker. Til 'm voorzichtig op." },
      { position: 6, body: "Snijd in punten. Bewaart twee dagen onder een omgekeerde kom op het aanrecht." },
    ],
  },
  {
    slug: "ceviche-witvis",
    title: "Witvis-ceviche met manzanilla",
    intro:
      "Daurade, kort getrokken in limoen, met een sherry-twist. Vijftien minuten van mes tot bord — geen vuur, alleen het zuur.",
    category: "voor",
    seasons: ["lente", "zomer"],
    difficulty: 2,
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 4,
    pairing: "Manzanilla en pasilla. Of een droge cava.",
    body: "Sleutel is een vissige vis die NIET overdreven vers ruikt — die heeft 'm gezien. Vraag de visboer om 'em zelf te fileren en de huid eraf te halen.",
    ingredients: [
      { quantity: "400 g", ingredient: "daurade-filet zonder huid (of zeebaars)" },
      { quantity: "3", ingredient: "limoenen, sap" },
      { quantity: "1", ingredient: "kleine rode ui, zo dun mogelijk gesneden" },
      { quantity: "1", ingredient: "rode pasilla peper, fijngehakt (zonder zaden voor minder pittig)" },
      { quantity: "1 hand", ingredient: "verse koriander, blaadjes geplukt" },
      { quantity: "2 el", ingredient: "manzanilla sherry" },
      { quantity: "1 el", ingredient: "olijfolie extra vergine" },
      { quantity: "naar smaak", ingredient: "vlokzout" },
      { group: "Erbij", quantity: "1", ingredient: "rijpe avocado in stukken" },
      { group: "Erbij", quantity: "1 hand", ingredient: "gepofte mais of geroosterde maïskorrels" },
    ],
    steps: [
      { position: 1, body: "Leg de filet 10 minuten in de vriezer — dan snijdt 'ie strakker. Snijd in dobbelstenen van een halve cm." },
      { position: 2, body: "Doe de visstukjes in een koude kom met de uiringen. Schenk het limoensap erover. Laat 5-7 minuten staan — niet langer, anders gaart de vis dwars door." },
      { position: 3, body: "Roer er manzanilla, olijfolie, pepertje en de helft van de koriander door. Proef op zout." },
      { position: 4, body: "Schep op vier koude borden. Werk af met avocado, maïs en de rest van de koriander. Vlokzout er bovenop." },
      { position: 5, body: "Eet binnen 10 minuten op. De vis verandert van textuur als je 'm laat staan en wordt ineens net vlees in plaats van zacht." },
    ],
  },
  {
    slug: "aioli-klassiek",
    title: "Aioli klassiek",
    intro:
      "De moeder van alle Spaanse sauzen. Knoflook, olie, een snufje zout — in een vijzel, geen blender. Geen ei nodig.",
    category: "basis",
    seasons: ["altijd"],
    difficulty: 3,
    prepMinutes: 20,
    cookMinutes: 0,
    servings: 6,
    body: "Dit is de Catalaanse versie zonder ei — alleen olie en knoflook die binden door geduld. Lukt of mislukt, geen tussenweg. Vooral niet haasten met de olie.",
    ingredients: [
      { quantity: "4 teentjes", ingredient: "verse knoflook, gepeld" },
      { quantity: "1/2 tl", ingredient: "fijn zeezout" },
      { quantity: "250 ml", ingredient: "milde olijfolie (geen extra vergine — die maakt 'm bitter)" },
      { quantity: "paar druppels", ingredient: "citroensap" },
    ],
    steps: [
      { position: 1, body: "Wrijf de knoflook met het zout in een vijzel tot een gladde pasta. Geen vijzel? Maak het op een snijplank met de zijkant van het mes." },
      { position: 2, body: "Begin de olie druppelsgewijs toe te voegen terwijl je continu roert — letterlijk druppel per druppel de eerste vijf minuten. Hier zit het werk." },
      { position: 3, body: "Zodra je een romige basis hebt, mag de stroom olie iets sneller. Blijf roeren in dezelfde richting." },
      { position: 4, body: "Werk door tot je een dikke, glanzende mayonaise-achtige saus hebt. Een paar druppels citroen om te balanceren." },
      { position: 5, body: "Schept op een tapasbord, of dip met gegrild brood en kort geroosterde groente. Bewaart één dag in de koelkast." },
    ],
  },
];
